treasurehunt:
  findtime: 60
  # Time players have to find the treasure (minutes)
  waittime: 60
  # Time to wait before spawning a new treasure after the time was up (minutes)

multiplayer:
  waitforplayers: 10
  # Time to wait for players before starting
  startcountdown: 5
  # Time before game actually starts
  timerMessageInterval:
    - 900
    - 600
    - 300
    - 60
    - 30
    - 10
  broadcastwin: true
  
spleef:
  floordegenerate:
    time: 30
    enabled: true
  
singleplayer:
  broadcastcompletion: true
  
use-sql: false
sql-host: localhost
sql-port: 3306
sql-database: database
sql-username: root
sql-password: root

outputCMDToFile: false

minigames:
  {}